<?php


namespace App\Tests\Controller;

use App\Context\Csv\CsvService;
use PHPUnit\Framework\TestCase;

class CsvServiceTest extends TestCase
{
    /**
     * @var CsvService
     */
    public $csvService;

    public $csvFileName;


    public function setUp()
    {
        $this->csvService = new CsvService('data.csv');
        $this->csvFileName = $this->csvService->getFileName();
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testFileExist()
    {
        $this->assertFileExists($this->csvFileName);
    }

    public function testFileIsReadable()
    {
        $this->assertFileIsReadable($this->csvFileName);
    }

    public function testGetCsv()
    {
        $this->assertTrue(is_array($this->csvService->getCsv()));
    }

    /**
     * @dataProvider setCsvDataProvider
     * @param string $data
     */
    public function testSetCsv(string $data)
    {
        $csvData = [$data];
        $this->csvService->setCsv($csvData);
        $csvReadData = $this->csvService->getCsv();
        $lastElement = end($csvReadData);
        $data = explode(';', $data);
        $this->assertEquals($data, $lastElement);
    }

    public function setCsvDataProvider()
    {
        return [
            [
                'Тест;Тестовое название организации;99999999'
            ],
            [
                'Тест2;Тестовое название организации2;11111111'
            ]
        ];
    }

}